# 原作人物与说话人定义。
define me = Character("我",color="#b9cbd4")
define mind = Character("内心", color="#b9cbd4")
define sayori = Character("Sayori", color="#ff66aa")
define cordelia = Character("Cordelia", color="#afbaff")
define obedience = Character("Obedience", color="#ffaa00")
define monika = Character("Monika", color="#9bdbaf")
define teacher = Character("老师", color="#afbaff")
define leo = Character("Leo", color="#e1a9ee")
define stranger = Character("陌生人",color="#9bdbaf")
define waiter = Character("服务员")
define shane = Character("Shane", color="#aaddff")
define DDOS = Character("Ddos")
define everyone = Character("Everyone")
define paper = Character("Paper",color="#afbaff")
define staff = Character("Staff")
define cast_all = Character("Monika、sayori、cordelia、obedience、我、shane、teacher")
define 微信里的me = Character("微信里的me",color="#b9cbd4")
define 微信里的shane = Character("微信里的shane",color="#aaddff")
define 门的对面 = Character("门的对面",color="#ff66aa")
define dorm_staff = Character("Dorm Staff")
define mysterious_voice = Character("Voice",color="#9bdbaf")
define everyone_else = Character("Everyone Else")
define 尚睿洋 = Character("尚睿洋")
define mxnika = Character("Mxnika",color="#9bdbaf")
define mxnlke = Character("Mxnlke",color="#9bdbaf")
define telephone = Character("Telephone")
define nnxnIk3 = Character("Nnxnik3",color="#9bdbaf")
define obedience_and_cordelia = Character("Obedience And Cordelia")
define DDLC = Character("Ddlc")
define 微信里的sayori = Character("微信里的sayori",color="#ff66aa")
define 回忆中的sayori = Character("回忆中的sayori",color="#ff66aa")
define O_mind = Character("obedience的内心",color="#afbaff")
define log = Character("Log",color="#9bdbaf")
define 吐出了东西的sayori = Character("吐出了东西的sayori",color="#ff66aa")
define clerk = Character("Clerk")
define C_mind = Character("cordelia的内心",color="#afbaff")
define 嘴里堵着东西且被捆起来的sayori = Character("嘴里堵着东西且被捆起来的sayori",color="#ff66aa")
define cordelia_and_obedience = Character("Cordelia And Obedience")
define 记忆里的me = Character("记忆里的me",color="#b9cbd4")
define S_mind = Character("sayori的内心",color="#ff66aa")
define 微信里的助教 = Character("微信里的助教")
define evryone_except_monika_and_sayori = Character("Evryone Except Monika And Sayori")
define mix = Character("Mix")
define mom = Character("Mom")
define cordelia的舍友 = Character("Cordelia的舍友")
define obedience的舍友 = Character("Obedience的舍友")
